2021-10-14 18:55:28,378 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 18:55:35,863 django.request ERROR    Internal Server Error: /api/v1/news/
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azamat/Рабочий стол/Django/social/soc_api/views.py", line 76, in get
    return JsonResponse(serializer.data)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2021-10-14 18:57:20,316 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/social/settings.py changed, reloading.
2021-10-14 18:57:20,742 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 18:57:22,990 django.request ERROR    Internal Server Error: /api/v1/news/
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azamat/Рабочий стол/Django/social/soc_api/views.py", line 76, in get
    return JsonResponse(serializer.data)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2021-10-14 18:57:23,085 django.request WARNING  Not Found: /favicon.ico
2021-10-14 18:58:20,684 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 18:58:21,163 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 18:58:47,193 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 18:58:47,594 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:00:11,394 django.request WARNING  Not Found: /favicon.ico
2021-10-14 19:01:02,971 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:01:03,420 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:01:43,970 django.request WARNING  Bad Request: /api/v1/news/
2021-10-14 19:02:06,816 django.request WARNING  Not Found: /api/v1/
2021-10-14 19:02:06,846 django.request WARNING  Not Found: /favicon.ico
2021-10-14 19:02:15,401 django.request ERROR    Internal Server Error: /api/v1/news/
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azamat/Рабочий стол/Django/social/soc_api/views.py", line 76, in get
    return JsonResponse(serializer.data)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2021-10-14 19:02:27,731 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:02:28,146 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:03:28,897 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:03:29,346 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:03:30,784 django.request WARNING  Not Found: /favicon.ico
2021-10-14 19:04:22,930 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:04:23,328 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:05:45,571 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:05:45,989 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:07:16,413 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:07:16,773 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:07:27,368 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:07:27,798 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:07:50,745 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:07:51,145 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:07:57,170 django.request WARNING  Bad Request: /api/v1/posts/
2021-10-14 19:08:18,211 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:08:18,565 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:08:26,920 django.request WARNING  Bad Request: /api/v1/posts/
2021-10-14 19:10:54,321 django.request ERROR    Internal Server Error: /api/v1/posts
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/v1/posts/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2021-10-14 19:11:25,304 django.request WARNING  Bad Request: /api/v1/news/
2021-10-14 19:11:48,217 django.request WARNING  Bad Request: /api/v1/news/
2021-10-14 19:13:20,580 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:13:20,950 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:20:44,658 django.request WARNING  Not Found: /news/
2021-10-14 19:21:34,945 django.request WARNING  Not Found: /news/
2021-10-14 19:22:06,426 django.request WARNING  Not Found: /news/
2021-10-14 19:27:49,763 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:27:50,382 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:29:44,333 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:29:44,742 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:30:08,691 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/urls.py changed, reloading.
2021-10-14 19:30:09,075 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:30:21,591 django.request ERROR    Internal Server Error: /api/v1/show_posts/
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azamat/Рабочий стол/Django/social/soc_api/views.py", line 120, in show_all_news
    return render(request, 'soc_api/index.html', posts=posts)
TypeError: render() got an unexpected keyword argument 'posts'
2021-10-14 19:31:16,029 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:31:16,444 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:34:00,518 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:34:00,904 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:35:20,091 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:35:20,438 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:37:39,455 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:37:39,938 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:37:44,247 django.request WARNING  Not Found: /favicon.ico
2021-10-14 19:38:09,005 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:38:09,460 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:38:11,381 django.request ERROR    Internal Server Error: /api/v1/show_posts/
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azamat/Рабочий стол/Django/social/soc_api/views.py", line 123, in show_all_news
    print("Кол во записей в бд: " + str(len(posts)) + "\n" + "Время выполнения запроса: " + str(round(time_after - time_before), 3))
TypeError: str() argument 2 must be str, not int
2021-10-14 19:38:21,219 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:38:21,617 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:41:12,690 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:41:13,084 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:41:52,364 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:41:52,945 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:42:34,779 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:42:35,241 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:51:11,497 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:51:11,857 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:51:41,744 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/urls.py changed, reloading.
2021-10-14 19:51:42,106 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:51:48,723 django.request WARNING  Not Found: /api/v1/
2021-10-14 19:51:57,642 django.request WARNING  Bad Request: /api/v1/news/
2021-10-14 19:55:45,112 django.request WARNING  Bad Request: /api/v1/posts/
2021-10-14 19:56:17,344 django.request WARNING  Not Found: /favicon.ico
2021-10-14 21:40:13,679 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 21:40:16,451 django.request WARNING  Not Found: /favicon.ico
2021-10-14 21:43:03,043 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 21:43:03,458 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 21:43:19,125 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 21:43:19,471 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 21:44:27,452 django.request WARNING  Bad Request: /api/v1/posts/
2021-10-14 21:44:56,030 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 21:50:35,273 soc.views    INFO     Post values: {'title': 'ewd', 'text': 'wddwd', 'image': None, 'user_id': 1}
2021-10-14 21:50:35,280 soc.service.content_service INFO     Пост  5|ewd был добавлен пользователем 1|Azamatik
2021-10-14 21:53:00,296 django.security.csrf WARNING  Forbidden (CSRF cookie not set.): /accounts/login/
2021-10-14 21:54:17,784 django.security.csrf WARNING  Forbidden (CSRF cookie not set.): /accounts/login/
2021-10-14 22:09:16,725 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:09:17,084 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:09:59,295 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/urls.py changed, reloading.
2021-10-14 22:09:59,678 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:10:12,440 django.request WARNING  Not Found: /api/v1/posts/10
2021-10-14 22:10:18,045 django.request WARNING  Not Found: /api/v1/posts/1
2021-10-14 22:10:20,978 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:13:06,032 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:13:06,611 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:13:57,051 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/urls.py changed, reloading.
2021-10-14 22:13:57,644 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:15:09,648 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:15:10,034 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:16:57,544 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:16:57,907 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:17:26,111 django.request WARNING  Forbidden: /api/v1/users/
2021-10-14 22:22:23,294 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:22:23,729 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:24:28,939 django.utils.autoreload INFO     Watching for file changes with StatReloader
